// <auto-generated />
using System;
using EasyPanel.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyPanel.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911001223_AddNodeSystemStats")]
    partial class AddNodeSystemStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text")
                        .HasColumnName("details_json");

                    b.Property<Guid?>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("ActorUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_log_entries_actor_user_id_created_at_utc");

                    b.HasIndex("InstanceId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_log_entries_instance_id_created_at_utc");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRestartEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_restart_enabled");

                    b.Property<int?>("CpuLimitPercent")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_limit_percent");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EnvironmentVariablesJson")
                        .HasColumnType("text")
                        .HasColumnName("environment_variables_json");

                    b.Property<string>("ExecutableRelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executable_relative_path");

                    b.Property<string>("ExpectedExecutableSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_executable_sha256");

                    b.Property<string>("LaunchArguments")
                        .HasColumnType("text")
                        .HasColumnName("launch_arguments");

                    b.Property<int?>("MemoryLimitMegabytes")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_megabytes");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkDirectory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_directory");

                    b.HasKey("Id")
                        .HasName("pk_instances");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_instances_node_id");

                    b.ToTable("instances", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AvailableMemoryMegabytes")
                        .HasColumnType("bigint")
                        .HasColumnName("available_memory_megabytes");

                    b.Property<int>("ConnectivityMode")
                        .HasColumnType("integer")
                        .HasColumnName("connectivity_mode");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DaemonVersion")
                        .HasColumnType("text")
                        .HasColumnName("daemon_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("HostName")
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<int?>("LogicalProcessorCount")
                        .HasColumnType("integer")
                        .HasColumnName("logical_processor_count");

                    b.Property<string>("NodeTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_token_hash");

                    b.Property<long?>("TotalPhysicalMemoryMegabytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_physical_memory_megabytes");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.PortAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.HasKey("Id")
                        .HasName("pk_port_allocations");

                    b.HasIndex("NodeId", "Port", "Protocol")
                        .IsUnique()
                        .HasDatabaseName("ix_port_allocations_node_id_port_protocol");

                    b.ToTable("port_allocations", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.StaffServerPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanAccessFileManager")
                        .HasColumnType("boolean")
                        .HasColumnName("can_access_file_manager");

                    b.Property<bool>("CanControlPower")
                        .HasColumnType("boolean")
                        .HasColumnName("can_control_power");

                    b.Property<bool>("CanEditSettings")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_settings");

                    b.Property<bool>("CanSendConsoleInput")
                        .HasColumnType("boolean")
                        .HasColumnName("can_send_console_input");

                    b.Property<bool>("CanViewConsole")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view_console");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_server_permissions");

                    b.HasIndex("UserId", "InstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_server_permissions_user_id_instance_id");

                    b.ToTable("staff_server_permissions", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EasyPanel.Backend.Infrastructure.Entities.Instance", b =>
                {
                    b.HasOne("EasyPanel.Backend.Infrastructure.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instances_nodes_node_id");

                    b.Navigation("Node");
                });
#pragma warning restore 612, 618
        }
    }
}
